/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\WoodenPallet.glb -o .\components\3DObjects\PalletModel.tsx -r public 
*/

import * as THREE from 'three'
import React, { RefObject } from 'react'
import { Edges, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'
import { SimBatch, SimPallet } from '../SimCanvas'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    Crate: THREE.MeshStandardMaterial
  }
}


type palletprops = ThreeElements['group'] & {
  data: SimBatch | SimPallet,
  renderScale: number,
  meshRef?: RefObject<THREE.Mesh>,
}

export function PalletModel(props: palletprops) {
  const { nodes, materials } = useGLTF('/models/WoodenPallet.glb') as GLTFResult

  const adjustScale = (size: [number, number, number]): [number, number, number] => {
    return size.map(v => v / props.renderScale) as [number, number, number]
  }
  const loadSize: [number, number, number] = adjustScale([props.data.loadlength, props.data.loadheight, props.data.loadwidth])
  const palletSize: [number, number, number] = adjustScale([props.data.length, props.data.height, props.data.width])

  return (
    <group {...props} dispose={null}>
      <mesh position={[0, loadSize[1] / 2, 0]} ref={props.meshRef} scale={loadSize}>
        <boxGeometry />
        <meshStandardMaterial transparent opacity={0} />
        <Edges lineWidth={2} color={"black"} transparent opacity={0.5} />
      </mesh >
      <mesh geometry={nodes.Cube.geometry} material={materials.Crate} position={[0, palletSize[1] * -1.04886, 0]} scale={[palletSize[0] * 0.164399, palletSize[1] * 0.89659, palletSize[2] * 0.139778]} />
    </group>
  )
}

useGLTF.preload('/models/WoodenPallet.glb')
