/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\ShipContainer.glb -o .\components\3DObjects\ShipContainerModel.tsx -r public 
*/

import * as THREE from 'three'
import React, { RefObject } from 'react'
import { Edges, Mask, useGLTF, useMask } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'
import { SimBatch } from '../SimCanvas'

type GLTFResult = GLTF & {
  nodes: {
    Left: THREE.Mesh
    Right: THREE.Mesh
    ['Node-Mesh063']: THREE.Mesh
    ['Node-Mesh063_1']: THREE.Mesh
    Back: THREE.Mesh
    ['Node-Mesh070']: THREE.Mesh
    ['Node-Mesh070_1']: THREE.Mesh
    ['Node-Mesh070_2']: THREE.Mesh
    ['Node-Mesh070_3']: THREE.Mesh
    ['Node-Mesh070_4']: THREE.Mesh
    Top: THREE.Mesh
    Bottom: THREE.Mesh
  }
  materials: {
    mat14: THREE.MeshStandardMaterial
    mat23: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat12: THREE.MeshStandardMaterial
  }
}


type ShipContainerProps = ThreeElements['group'] & {
  data: SimBatch,
  renderScale: number,
  meshRef: RefObject<THREE.Mesh>, isSeethrough: boolean,
}

export function ShipContainerModel(props: ShipContainerProps) {
  const { nodes, materials } = useGLTF('/models/ShipContainer.glb') as GLTFResult

  const adjustScale = (size: [number, number, number]): [number, number, number] => {
    return size.map(v => v / props.renderScale) as [number, number, number]
  }
  const loadSize: [number, number, number] = adjustScale([props.data.loadlength, props.data.loadheight, props.data.loadwidth])
  const contSize: [number, number, number] = adjustScale([props.data.length, props.data.height, props.data.width])


  const leftStencil = useMask(1, true)
  const leftMaterial = materials.mat14.clone()

  const rightStencil = useMask(2, true)
  const rightMaterial = materials.mat14.clone()

  const backStencil = useMask(3, true)
  const backMaterial = materials.mat14.clone()

  const topStencil = useMask(4, true)
  const topMaterial = materials.mat14.clone()

  const frontStencil = useMask(5, true)
  const frontMaterial12 = materials.mat12.clone()
  const frontMaterial14 = materials.mat14.clone()
  const frontMaterial15 = materials.mat15.clone()
  const frontMaterial16 = materials.mat16.clone()
  const frontMaterial23 = materials.mat23.clone()

  if (props.isSeethrough) {
    Object.assign(leftMaterial, leftStencil)
    Object.assign(rightMaterial, rightStencil)
    Object.assign(backMaterial, backStencil)
    Object.assign(topMaterial, topStencil)
    Object.assign(frontMaterial12, frontStencil)
    Object.assign(frontMaterial14, frontStencil)
    Object.assign(frontMaterial15, frontStencil)
    Object.assign(frontMaterial16, frontStencil)
    Object.assign(frontMaterial23, frontStencil)
  }

  return (
    <group {...props} dispose={null}>
      <mesh position={[0, loadSize[1] / 2, 0]} ref={props.meshRef} scale={loadSize}>
        <boxGeometry />
        <meshStandardMaterial transparent opacity={0} />
        <Edges lineWidth={2} color={"black"} transparent opacity={0.5} />
      </mesh >

      <group position={[0, 0, 0]} scale={[contSize[0] * 0.848536, contSize[1] * 0.848536, contSize[2] * 0.848536]}>
        <mesh geometry={nodes.Bottom.geometry} material={materials.mat14} />
        <mesh geometry={nodes['Node-Mesh063_1'].geometry} material={materials.mat14} />

        {/* corner holes */}
        <mesh geometry={nodes['Node-Mesh063'].geometry} material={materials.mat23} />

        <mesh geometry={nodes.Left.geometry} material={leftMaterial} />
        <Mask position={[0.59, 0.51, 0]} scale={1.18} rotation={[0, Math.PI / 2, 0]} id={1}>
          <planeGeometry />
          <meshBasicMaterial />
        </Mask>
        <mesh geometry={nodes.Right.geometry} material={rightMaterial} />
        <Mask position={[-0.59, 0.51, 0]} scale={1.18} rotation={[0, -Math.PI / 2, 0]} id={2}>
          <planeGeometry />
          <meshBasicMaterial />
        </Mask>
        <mesh geometry={nodes.Back.geometry} material={backMaterial} />
        <Mask position={[0, 0.51, 0.59]} scale={1.18} rotation={[0, 0, 0]} id={3}>
          <planeGeometry />
          <meshBasicMaterial />
        </Mask>
        <mesh geometry={nodes.Top.geometry} material={topMaterial} />
        <Mask position={[0, 1.1, 0]} scale={1.18} rotation={[-Math.PI / 2, 0, 0]} id={4}>
          <planeGeometry />
          <meshBasicMaterial />
        </Mask>

        <mesh geometry={nodes['Node-Mesh070'].geometry} material={frontMaterial15} />
        <mesh geometry={nodes['Node-Mesh070_1'].geometry} material={frontMaterial23} />
        <mesh geometry={nodes['Node-Mesh070_2'].geometry} material={frontMaterial14} />
        <mesh geometry={nodes['Node-Mesh070_3'].geometry} material={frontMaterial16} />
        <mesh geometry={nodes['Node-Mesh070_4'].geometry} material={frontMaterial12} />
        <Mask position={[0, 0.51, -0.59]} scale={1.18} rotation={[0, Math.PI, 0]} id={5}>
          <planeGeometry />
          <meshBasicMaterial />
        </Mask>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ShipContainer.glb')
